#ifndef LIBPAS_ACP_CHANNEL_H
#define LIBPAS_ACP_CHANNEL_H

#define ACP_CMD_CHANNEL_STOP "csp"
#define ACP_CMD_CHANNEL_START "cst"
#define ACP_CMD_CHANNEL_RESET "crs"
#define ACP_CMD_CHANNEL_ENABLE "cenl"
#define ACP_CMD_CHANNEL_DISABLE "cdsl"
#define ACP_CMD_CHANNEL_ADD "cadd"
#define ACP_CMD_CHANNEL_DELETE "cdel"
#define ACP_CMD_CHANNEL_GET_DATA_RUNTIME "cgdr"
#define ACP_CMD_CHANNEL_GET_DATA_INIT "cgdi"
#define ACP_CMD_CHANNEL_GET_INFO "cgi"
#define ACP_CMD_CHANNEL_GET_DATA "cgd"
#define ACP_CMD_CHANNEL_GET_ENABLED "cgenl"
#define ACP_CMD_CHANNEL_SET_SAVE "cssave"
#define ACP_CMD_CHANNEL_GET_ERROR "cgerr"

#endif

